config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  resources :listings, controller: "listings"

  resources :listings do 
     resources :reservations
  end

  resources :reservations, only: [:destroy]

  resources :tags, controller: "tags" do
   resource :listings, controller: "tags"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  
  resources :users
  resources :users, controller: "users", only: [:create, :new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users do
     resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/reservations/:rid/transactions/new" => "transactions#new", as: "transactions_new"
  post '/reservations/:rid/transactions/checkout' => "transactions#checkout", as: "transactions_checkout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  mount_uploader :avatar, AvatarUploader
 
  has_many :authentications, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  has_many :reservations, :dependent => :destroy

  enum status: [:customer, :superadmin, :moderator]
  enum gender: [:undefined, :male, :female]

  #validates_format_of :email, :with => /^[\+A-Z0-9\._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i

	def self.create_with_auth_and_hash(authentication, auth_hash)
    create! do |u|
       u.full_name = auth_hash["info"]["name"]
       u.email = auth_hash["extra"]["raw_info"]["email"]
       u.gender = auth_hash["extra"]["raw_info"]["gender"]
	     #user = User.create!(full_name: auth_hash["info"]["name"], email: auth_hash["extra"]["raw_info"]["email"])
	     u.authentications << (authentication)      
       u.password = SecureRandom.hex(7)
    end  
	end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

    # def password_optional?
    #   true #if login with FB then true, else false
    # end 

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def show
		@user = User.find(params[:id])
	end	

	def edit
		@user = User.find(params[:id])
	end	

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to @user
	end	

	def create
	    @user = user_from_params
	    
	    if @user.save
	      sign_in @user
	      redirect_back_or url_after_create
	    else
	      render template: "users/new"
	    end
	end

	private
	def user_params
		params.require(:user).permit(:full_name, :email, :password, :gender, :age, :avatar, :remove_avatar)
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<br>
<form name="registration",>
  <div class="name-field">
    <p class="login-input">FULL NAME:</p>
    <%= form.text_field :full_name %>
  </div>

  <br>
  <div class="avatar">
     <p class="login-input">UPLOAD PICTURE:</p><i> (Optional)</i></p>
    <%= form.file_field :avatar %>
  </div> 

  <br>
  <div class="gender-field"> 
    <p class="login-input">GENDER:</p>
    <%= form.select :gender, options_for_select([["undefined", :undefined], ["male", :male], ["female", :female]])%>
  </div>

  <br>
  <div class="age-field">
    <p class="login-input">AGE:</p>
    <%= form.number_field :age %>
  </div>

  <br>
  <div class="email-field">
    <p class="login-input">E-MAIL:</p>
    <%= form.text_field :email %>
  </div>

  <br>
  <div class="password-field">
    <p class="login-input">PASSWORD:</p>
    <%= form.password_field :password %>
  </div>    

  <br>
  <div class="submit-field">
    <%= form.submit %>
  </div>
</form>

app/views/users/edit.html.erb
<br>
<div style="font-family: 'Comfortaa', cursive; font-size: 30px;">UPDATE PROFILE</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6 left">

	      <%= form_for @user do |form| %>
	      <div class="name-field">
          <%= form.label :full_name %>
          <%= form.text_field :full_name %>
        </div>

        <% if current_user.avatar.url.present? %>
           <%= image_tag(current_user.avatar.url) %>
           <%= form.label :remove_avatar do %>
             <%= form.check_box :remove_avatar %>
             <% @user.remove_avatar!%>
             Remove avatar
           <% end %>
         <% end %>
         <%= form.file_field :avatar %>
         <%= form.hidden_field :avatar_cache %>  

        <div class="gender-field"> 
          <%= form.label :gender %>
          <%= form.select :gender, options_for_select([["undefined", :undefined], ["male", :male], ["female", :female]])%>
        </div>

        <div class="age-field">
          <%= form.label :age %>
          <%= form.number_field :age %>
        </div>

        <div class="email-field">
          <%= form.label :email %>
          <%= form.text_field :email %>
        </div>

        <div class="password-field">
          <%= form.label :password %><i>(we need your current password to confirm your changes)</i>
          <%= form.password_field :password %>
        </div>

        <br>
        <div><%= link_to 'Cancel', @user %> <%= form.submit "Update" %></div>
        <%end%>
      </div>

       <div class="col-md-6 right">
       </div> 

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2 style="font-family: 'Comfortaa', cursive;">Mingle</h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="other-links">
      Have account? Please <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<body style="padding-left: 60px;">

  <% if @user.avatar? %>
  	<%= image_tag @user.avatar.thumb.url, :class => "img-responsive img-circle" %>
  <% else %> 
    <img src="..." alt="...">
  <%end%>

  <h1>Welcome <%= @user.full_name %></h1>
  <div><%= link_to "Edit Profile", edit_user_path(@user)%></div>
  <% if !current_user.customer? %>
    <div><%= link_to "View listings", user_listings_path(@user.id)%></div>
  <% end %>

  <% if current_user && current_user.id == @user.id %>
  <h2>Listings</h2>
    <table class="table table-striped">
      <tr>
        <th>Title</th>
        <th>Actions</th>
      </tr>

      <% @user.listings.each do |listing| %>
        <tr>
          <td><%= link_to listing.title, listing %></td>
          <td><%= link_to "Edit", edit_listing_path(listing) %> | <%= link_to "Delete", listing, method: :delete, data: { confirm: "Are you super duper sure?" } %></td>
        </tr>
      <% end %>
    </table>


     <h2>Reservations</h2>
       <table class="table table-striped">
         <tr>
           <th>Listing Title</th>
           <th>Start Date</th>
           <th>End Date</th>
           <th>Num Guests</th>
           <th>Total Price</th>
           <th>Actions</th>
         </tr>

         <% @user.reservations.each do |booking| %>
           <tr>
             <td><%= link_to booking.listing.title, booking.listing %></td>
             <td><%= booking.start_date.strftime('%d %B %Y') %></td>
             <td><%= booking.end_date.strftime('%d %B %Y') %></td>
             <td><%= booking.num_guests %></td>
             <td>RM <%= booking.total_price %></td>
             <td><%= link_to "Cancel Booking", booking, method: :delete, data: { confirm: "You don't want to Mingle?" } %></td>
           </tr>
         <% end %>
       </table>
   <%end%>

</body>

<div class="area"></div><nav class="main-menu">
     <ul>
         <li>
             <a href="#">
                 <i class="fa fa-user-circle fa-2x"></i>
                 <span class="nav-text">
                     Profile
                 </span>
             </a>
           
         </li>
         <li>
             <a href="#">
                 <i class="fa fa-home fa-2x"></i>
                 <span class="nav-text">
                     Inbox
                 </span>
             </a>
           
         </li>
         <li class="has-subnav">
             <a href="#">
                 <i class="fa fa-laptop fa-2x"></i>
                 <span class="nav-text">
                     Past Transactions
                 </span>
             </a>
             
         </li>
         <li class="has-subnav">
             <a href="#">
                <i class="fa fa-list fa-2x"></i>
                 <span class="nav-text">
                     History
                 </span>
             </a>
             
         </li>
         <li class="has-subnav">
             <a href="#">
                <i class="fa fa-folder-open fa-2x"></i>
                 <span class="nav-text">
                     Pages
                 </span>
             </a>
            
         </li>
         <li>
             <a href="#">
                 <i class="fa fa-bar-chart-o fa-2x"></i>
                 <span class="nav-text">
                     Graphs and Statistics
                 </span>
             </a>
         </li>
         <li>
             <a href="#">
                 <i class="fa fa-font fa-2x"></i>
                 <span class="nav-text">
                     Typography and Icons
                 </span>
             </a>
         </li>
         <li>
            <a href="#">
                <i class="fa fa-table fa-2x"></i>
                 <span class="nav-text">
                     Calender
                 </span>
             </a>
         </li>       
         <li>
             <a href="#">
                <i class="fa fa-info fa-2x"></i>
                 <span class="nav-text">
                     Documentation
                 </span>
             </a>
         </li>
     </ul>

     <ul class="logout">
         <li>
            <a href="#">
                  <i class="fa fa-power-off fa-2x"></i>
                 <span class="nav-text">
                     Logout
                 </span>
             </a>
         </li>  
     </ul>
 </nav>

  