config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  resources :listings, controller: "listings"

  resources :listings do 
     resources :reservations
  end

  resources :reservations, only: [:destroy]

  resources :tags, controller: "tags" do
   resource :listings, controller: "tags"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  
  resources :users
  resources :users, controller: "users", only: [:create, :new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users do
     resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/reservations/:rid/transactions/new" => "transactions#new", as: "transactions_new"
  post '/reservations/:rid/transactions/checkout' => "transactions#checkout", as: "transactions_checkout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :listings, through: :listing_tags
	has_many :listing_tags, :dependent => :destroy
	# enum tag_content: [:smoking, :wifi, :pets, :non_smoking, :non_wifi, :non_pets]
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :logged_in_user, only: [:new, :create]
	before_action :find_tag, only: [:show, :delete, :edit, :update]

	def index
		@show_tag = Tag.all
		@tags = Tag.all
		@tag = Tag.new
	end
	
	def new
		@tag = Tag.new
	end

	def create
		@listing = Listing.find(params[:id])
		@tag = Tag.new(tag_params)
		
		if @tag.save
			redirect_to @listing
		else
			"ERROR"
			render root_path	
		end	
	end

	def destroy
		@tag.destroy
		redirect_to listings_path
	end

	def show
		@tags = Tag.all
	end

	private 
	def find_tag
		@tag = Tag.find(params[:tag_id])
	end

	def tag_params
	    params.require(:tag).permit(:tag_content)
	end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="tag-field"> 
  <%= form.label :tag_content %>
    <%= radio_button_tag(:tag_content, :smoking) %>
    <%= label_tag(:tag_content, "smoking") %>
    <%= radio_button_tag(:tag, :non_smoking) %>
    <%= label_tag(:gender_person, "non-smoking") %>
    <%= radio_button_tag(:tag_content, :wifi) %>
    <%= label_tag(:tag_content, "wifi") %>
    <%= radio_button_tag(:tag, :non_wifi) %>
    <%= label_tag(:gender_person, "non-wifi") %>
    <%= radio_button_tag(:tag_content, :pets) %>
    <%= label_tag(:tag_content, "pets") %>
    <%= radio_button_tag(:tag, :non_pets) %>
    <%= label_tag(:gender_person, "non-pets") %>
</div>

app/views/tags/show.html.erb
 <div class="container">
	<div class="row">
		<% @tag.listings.each do |l|%>
		<div class="column">
			<div class="promos">  
				<div class="promo scale">
				  <div class="deal">
				    <span><%= link_to l.title, listing_path(l.id) %></span>
				    <span><%= l.description %></span>
				  </div>
				  <span class="price">RM<%= l.price %></span>
				  <ul class="features">
				    <li><%= l.place_type %></li>
				    <li><%= l.bedroom %> rooms</li>
				    <li><%= l.guest %> guests</li>  
				    <li><%l.tags.each do |t|%>
					    <%=link_to "#{t.tag_content}", tag_listings_path(t.id)%><br>
					    <%end%>
				    </li>
				  </ul>
				</div>
			</div>
		</div>	
		<%end%>
	</div>
</div>