config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  resources :listings, controller: "listings"

  resources :listings do 
     resources :reservations
  end

  resources :reservations, only: [:destroy]

  resources :tags, controller: "tags" do
   resource :listings, controller: "tags"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  
  resources :users
  resources :users, controller: "users", only: [:create, :new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users do
     resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/reservations/:rid/transactions/new" => "transactions#new", as: "transactions_new"
  post '/reservations/:rid/transactions/checkout' => "transactions#checkout", as: "transactions_checkout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	# before_action :check_cart!

	def new
	  @client_token = Braintree::ClientToken.generate
	  @reservation = Reservation.find(params[:rid])
	end

	def checkout
	  reservation = Reservation.find(params[:rid])
	  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

	  result = Braintree::Transaction.sale(
	   #:amount => session[:total_price]
	   :amount => reservation.total_price, #this is currently hardcoded
	   :payment_method_nonce => nonce_from_the_client,
	   :options => {
	      :submit_for_settlement => true
	    }
	   )
	  
	  if result.success?
	    redirect_to :root, :flash => { :success => "Transaction successful!" }
	  else
	    redirect_to :root, :flash => { :alert => "Transaction failed. Please try again." }
	  end 
	end

    # private
    # def check_cart!
    #   if current_user.reservations.blank?
    #     redirect_to root_url, alert: "Please add a booking date before processing your transaction!"
    #   end
    # end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/new.html.erb
<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<h1 id="payment">Payment</h1>
  <!-- Bootstrap inspired Braintree Hosted Fields example -->
<div class="demo-frame">  
    <%=  form_for :checkout_form, url: transactions_checkout_path, html: { id: "cardForm"} do |form| %>

      <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
      <div id="card-number" class="hosted-field"></div>

      <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>      
      <div id="expiration-date" class="hosted-field"></div>

      <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
      <div id="cvv" class="hosted-field"></div>

      <%= form.hidden_field "payment_method_nonce" %>
      <div><p>Total price: RM<%= @reservation.total_price %></p></div>

      <div class="button-container">
        <%= form.submit "Purchase", :"data-no-turbolink" => true, class: "btn btn-success btn-lg center-block", id: "submit-payment-btn" %>
      </div>
    <% end %>

  </div>
  
<script>

  var submit = document.querySelector("#submit-payment-btn");
  var form = document.querySelector('#cardForm');

  braintree.client.create({
  // Replace this with your own authorization.
  authorization: '<%= @client_token %>'

  }, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        
        form.submit();
      });
    }, false);
  });
  });

</script>