config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"

  resources :listings, controller: "listings"

  resources :listings do 
     resources :reservations
  end

  resources :reservations, only: [:destroy]

  resources :tags, controller: "tags" do
   resource :listings, controller: "tags"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]
  
  resources :users
  resources :users, controller: "users", only: [:create, :new] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users do
     resources :listings
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "/reservations/:rid/transactions/new" => "transactions#new", as: "transactions_new"
  post '/reservations/:rid/transactions/checkout' => "transactions#checkout", as: "transactions_checkout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mingle</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <script src="https://cdn.jsdelivr.net/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Inknut+Antiqua" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
</head>

<body>

<div id="header">
    <% if signed_in? -%>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">

        <div class="navbar-header">
          <%= link_to 'Mingle', root_path, class: 'navbar-brand', id: 'mingle-logo' %>
          
            <span class= 'navbar-brand' id="main" style="font-size:15px;cursor:pointer" onclick="openNav()">&#9776; more info</span> 
              <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
                 <%= text_field_tag :search, params[:search], placeholder: "location", class: "form-control", style: "margin:auto; width:200px;" %>

                <% end %>

                <%= link_to "Become a host", new_listing_path %>

                <p>Tags:</p>
                  <% Tag.all.each do |t|%>
                  <%=link_to t.tag_content, tag_listings_path(t.id)%>
                <%end%>
              </div>
               
        </div>

        <div class="nav navbar-nav pull-right">
          
        <a href= "/users/<%=current_user.id%>" class='navbar-brand' style='font-size: 16px'> <span class='glyphicon glyphicon-user'></span> <%=current_user.full_name%> </a>
          <li>
          <% if current_user.avatar? %>
            <%= image_tag current_user.avatar.profile.url, :class => "img-responsive img-circle", :style => "margin-bottom: 3px; margin-right: 15px;" %>
          <% else %> 
            <img src="..." alt="...">
          <%end%>
          </li>
          <li><%= button_to t(".sign_out"), sign_out_path, method: :delete, class: "btn btn-info" %></li>
         </div> 
       </div>   

    <% else -%>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <li><%= link_to 'Mingle', root_path, class: 'navbar-brand', id: 'mingle-logo' %></li>   
        </div>

        <div class="nav navbar-nav navbar-right">
              <li><a data-toggle="modal" data-target="#mySignUpModal"><span class="glyphicon glyphicon-user" ></span> Sign Up</a></li>
              <li><a data-toggle="modal" data-target="#myLogInModal"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </div>

        <div class="container">
          <!-- Modal -->
          <div class="modal fade" id="mySignUpModal" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <h4 style="font-family: 'Comfortaa', cursive;">Sign up</h4>
                </div>
                <div class="modal-body">
                <%= form_for User.new do |form| %>
                  <%= render partial: '/users/form', object: form %>
                <% end %>
                 
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal" data-target="#myLogInModal">Log In?</button>
                </div>
              </div>
              
            </div>
          </div>

          <!-- Modal -->
          <div id="myLogInModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 style="font-family: 'Comfortaa', cursive;">Log In</h4>
                </div>
                <div class="modal-body">
                  <%= render 'sessions/form' %>              
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal" data-toggle="modal" data-target="#mySignUpModal">Sign Up?</button>
                </div>
              </div>

            </div>
          </div>
        </div>  
        </div>

    <% end -%>
  </div>

  <div class="container">
    <%= flash_messages %>
    <%= yield %>
  </div>

  <br>  <br>  <br>  <br>  <br>  <br>  <br> 

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-3"></div>

        <div class="col-md-6"><span class="column"> <p class="listing-header", style="text-align:center; margin:auto; font-size: 13px;"> created by Michelle Ler </p></span></div>

        <div class="col-md-3"></div>
      </div>
    </div>
  </footer>

</body>
</html>